//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acconting.DateLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccontingEntities : DbContext
    {
        public AccontingEntities()
            : base("name=AccontingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acconting> Acconting { get; set; }
        public virtual DbSet<AccontingType> AccontingType { get; set; }
        public virtual DbSet<CustomerTB> CustomerTB { get; set; }
        public virtual DbSet<Login> Login { get; set; }
    }
}
